execution_engine: asyncio

logger:
  transports: [console]
  level: debug

mcp:
  servers:
    erp:
      command: "python"
      args: ["erp_reconciliation_mcp.py"]
      description: "ERP reconciliation MCP server"
      readiness_timeout: 20
